Fix build error about undefined reference to `deinit_vita_mmap'
```
frontend/libretro.o: In function `retro_deinit':
libretro.c:(.text+0x3769): undefined reference to `deinit_vita_mmap'
collect2: error: ld returned 1 exit status
make: *** [pcsx_rearmed_libretro.so] Error 1
```
Introduced #68